
USE motelapp;

DROP FUNCTION IF EXISTS TotalPagosCliente;
DROP FUNCTION IF EXISTS ObtenerNombreCliente;



-- FUNCION 1 RETORNA TOTAL DE DINERO PAGADO POR CONCEPTO DE RESERVAS POR UN CLIENTE ESPECIFICO
DELIMITER //
CREATE FUNCTION TotalPagosCliente(CLIENTE_ID VARCHAR(15)) RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE TOTAL INT;
    SELECT SUM(VALORRESERVA) INTO TOTAL FROM RESERVA WHERE ID_CLIENTE = CLIENTE_ID;
    RETURN TOTAL;
END //
DELIMITER ;

--SELECT TotalPagosCliente('CLI005');
--DROP FUNCTION TotalPagosCliente;





-- FUNCION 2 RETORNA NOMBRE DEL CLIENTE PARA UN CODIGO DE RESERVA ESPECIFICO
DELIMITER //
CREATE FUNCTION ObtenerNombreCliente(ID_RESERVA VARCHAR(10)) RETURNS VARCHAR(100)
NO SQL
BEGIN
    DECLARE CLIENTE_NOMBRE VARCHAR(100);    
    SELECT CLIENTE.NOMBRE INTO CLIENTE_NOMBRE
    FROM RESERVA
    INNER JOIN CLIENTE ON CLIENTE.ID_CLIENTE = RESERVA.ID_CLIENTE    
    WHERE RESERVA.ID_RESERVA = ID_RESERVA;    
    RETURN CLIENTE_NOMBRE;
END
// DELIMITER ;

--SELECT ObtenerNombreCliente('RES5792586');
--DROP FUNCTION ObtenerNombreCliente;





