USE motelapp;


-- TRIGGERS PARA PROCESO DE AUDITORIA TABLA CLIENTE. ESCRIBE LOS MOVIMIENTOS EN LA TABLA CLIENTELOGS
DELIMITER //
-- Trigger para inserción
CREATE TRIGGER trigger_cliente_insert
AFTER INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO CLIENTELOGS (ACCION, ID_CLIENTE, NOMBRE_CLIENTE, FECHA_HORA)
    VALUES ('INSERT', NEW.ID_CLIENTE, NEW.NOMBRE, CURRENT_TIMESTAMP);
END //
DELIMITER ;


-- Trigger para actualización
DELIMITER //
CREATE TRIGGER trigger_cliente_update
AFTER UPDATE ON CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO CLIENTELOGS (ACCION, ID_CLIENTE, NOMBRE_CLIENTE, FECHA_HORA)
    VALUES ('UPDATE', NEW.ID_CLIENTE, NEW.NOMBRE, CURRENT_TIMESTAMP);
END //
DELIMITER ;


-- Trigger para eliminación
DELIMITER //
CREATE TRIGGER trigger_cliente_delete
AFTER DELETE ON CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO CLIENTELOGS (ACCION, ID_CLIENTE, NOMBRE_CLIENTE, FECHA_HORA)
    VALUES ('DELETE', OLD.ID_CLIENTE, OLD.NOMBRE, CURRENT_TIMESTAMP);
END //
DELIMITER ;