USE motelapp;

-- VISTA 1 CLIENTES CUMPLEAÑEROS DEL MES
CREATE OR REPLACE VIEW ClientesDeCumpleanosMesActual AS
SELECT
    CLIENTE.NOMBRE,
    CLIENTE.EMAIL,
    CLIENTE.FECHANACIMIENTO,
    CLIENTEESTADO.DESCRIPCION
FROM
    CLIENTE
INNER JOIN
    CLIENTEESTADO ON CLIENTE.ID_CLIENTEESTADO = CLIENTEESTADO.ID_CLIENTEESTADO
WHERE
    MONTH(CLIENTE.FECHANACIMIENTO) = MONTH(CURRENT_DATE()) AND
    CLIENTEESTADO.ID_CLIENTEESTADO = 1;
 

-- VISTA 2 TOP 3 CLIENTES CON MAS RESERVAS EN EL AÑO
CREATE OR REPLACE VIEW ClientesTopReservasAnual AS
(SELECT
    RESERVA.ID_CLIENTE,
    COUNT(*) AS NUMEROVISITAS,
    CLIENTE.NOMBRE,
    CLIENTE.EMAIL,
    CLIENTEESTADO.DESCRIPCION
FROM
    RESERVA
INNER JOIN
    CLIENTE ON RESERVA.ID_CLIENTE = CLIENTE.ID_CLIENTE
INNER JOIN
    CLIENTEESTADO ON CLIENTE.ID_CLIENTEESTADO = CLIENTEESTADO.ID_CLIENTEESTADO
WHERE
    YEAR(FECHA) = YEAR(CURRENT_DATE) AND
    CLIENTE.ID_CLIENTEESTADO = 1
GROUP BY
    RESERVA.ID_CLIENTE
ORDER BY
    NUMEROVISITAS DESC
LIMIT 3);


-- VISTA 3 RESERVAS PAGADAS CON TRANSFERENCIA ELECTRONICA
CREATE OR REPLACE VIEW ReservasPagadasConTransferencia AS
(SELECT
    MEDIODEPAGO.DESCRIPCION, 
	PAGO.FECHAPAGO, 
	PAGO.NUMBOLETA, 
	RESERVA.ID_RESERVA, 
	RESERVA.VALORRESERVA
FROM
	PAGO
	INNER JOIN
	MEDIODEPAGO ON PAGO.ID_MEDIODEPAGO = MEDIODEPAGO.ID_MEDIODEPAGO
	INNER JOIN
	RESERVA ON PAGO.ID_RESERVA = RESERVA.ID_RESERVA
WHERE
	MEDIODEPAGO.ID_MEDIODEPAGO = 1);


-- VISTA 4 RESERVAS PAGADAS CON WEBPAY
CREATE OR REPLACE VIEW ReservasPagadasConWebPay AS
(SELECT
	MEDIODEPAGO.DESCRIPCION, 
	PAGO.FECHAPAGO, 
	PAGO.NUMBOLETA, 
	RESERVA.ID_RESERVA, 
	RESERVA.VALORRESERVA
FROM
	PAGO
	INNER JOIN
	MEDIODEPAGO ON PAGO.ID_MEDIODEPAGO = MEDIODEPAGO.ID_MEDIODEPAGO
	INNER JOIN
	RESERVA ON PAGO.ID_RESERVA = RESERVA.ID_RESERVA
WHERE
	MEDIODEPAGO.ID_MEDIODEPAGO = 2);


-- VISTA 5 CLIENTES POR COMUNA
CREATE OR REPLACE VIEW ListadoDeClientesPorComuna AS
(SELECT
	CLIENTE.NOMBRE AS NOMBRE_CLIENTE, 
	CLIENTE.EMAIL, 
	CLIENTEESTADO.DESCRIPCION, 
	COMUNAS.NOMBRE AS NOMBRE_COMUNA
FROM
	CLIENTE
	INNER JOIN
	COMUNAS ON CLIENTE.ID_COMUNA = COMUNAS.ID_COMUNA
	INNER JOIN
	CLIENTEESTADO ON CLIENTE.ID_CLIENTEESTADO = CLIENTEESTADO.ID_CLIENTEESTADO
WHERE
	CLIENTEESTADO.ID_CLIENTEESTADO = 1
ORDER BY
	COMUNAS.ID_COMUNA ASC);